server {
    listen 80;
    server_name localhost;
    root /var/www/html/v2/web;
    index index.php index.html;
    resolver 127.0.0.11 valid=10s ipv6=off;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        set $php_upstream php:9000;
        fastcgi_pass $php_upstream;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.(ht|svn|git) {
        deny all;
    }
}
